micronaut:
  application:
    name: preferenceService
  server:
    port: ${SERVER_PORT:8081}
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:mysql://192.168.1.23:3306/preferencedb
    username: root
    password: root
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true